title: Meghan's First GitHub Page
author: Meghan Duprey
email: meghan.duprey@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first GitHub page. I'm going to use it to play around with markdown and learn GitHub pages

# social links
twitter_username: @meghanduprey
github_username:  https://github.com/meghanduprey

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
